### ISSUE TITLE
Crash beim App-Start

### ISSUE THREAD

**Issue by karen-sch** [socialc0de/refugees-welcome-app#1]
Hi  zusammen!
Ich habe mir das APK von eurer Seite heruntergeladen. Beim ersten Appstart habe ich mich mit meinem Google-Account angemeldet, seitdem crasht die App jedes Mal beim Starten:

```
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime: FATAL EXCEPTION: main
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.ArrayList.toString()' on a null object reference
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at de.pajowu.donate.az.onCreateView(ListTabFragment.java:57)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.support.v4.app.ah.a(FragmentManager.java:1026)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.support.v4.app.ah.a(FragmentManager.java:1207)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.support.v4.app.ah.f(FragmentManager.java:1572)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.support.v4.app.ah.b(FragmentManager.java:545)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.support.v4.app.ar.b(FragmentPagerAdapter.java:141)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2031)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1402)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:550)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
10-06 22:06:49.353 20980-20980/? E/AndroidRuntime:  at java.lang.reflect.Method.invoke(
```

**Comment by pajowu** [comment]
Vielen Dank für deine Rückmeldung. Ich habe das Problem in commit f4ba72b behoben. Probier doch mal die aktuellste Version via https://betas.to/urYFKbzW
